name: Create Sha256

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  create-sha256:
    name: Create sha256 file
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Pull changes
        run: git pull

      - name: Create sha256 file
        run: sha256sum whitelist.json > whitelist.json.sha256

      - name: Set git user
        uses: fregante/setup-git-user@v2

      - name: Check for changes
        run: git status

      - name: Stage changed files
        run: git add .

      - name: Commit changed files
        run: "git commit -m 'Action: Update `.sha256` file'"

      - name: Fetch from master
        run: git fetch origin master

      - name: Push code to master
        run: git push origin master